baseURL = "https://tarduspura.github.io/"
title = "Tardus Pura 的个人空间"
theme = "PaperMod"

# 生成设置
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

# 限制首页文章数量
paginate = 3

[params]
  homePostsRSS = true
  math = true              # 支持数学公式
  showMenuItems = 10
  comments = true
  mainSections = ["posts", "guide", "travel","her","contemplate","projects"]

[params.homeInfoParams]
  Title = "Hi，Tardus Pura here"
  Content = "知识 | 户外 | 创作"

[params.profileMode]
  enabled = false

[params.assets]
  # PaperMod 会自动加载 assets/css/extended/ 目录下的 CSS 文件
  # 无需手动指定 customCSS 


[params.giscus]
    repo = "tarduspura/tarduspura.github.io"
    repoID = "R_kgDOP1xBhA"
    category = "comments"
    categoryID = "DIC_kwDOP1xBhM4Cw4e7"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "zh-CN"
    loading = "lazy"

   

# -------------------------------
# 菜单配置（统一管理）
# -------------------------------
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "笔记"
  url = "/posts"
  weight = 3

[[menu.main]]
  identifier = "travel"
  name = "旅行&户外"
  url = "/travel"
  weight = 4

[[menu.main]]
  identifier = "contemplate"
  name = "沉思"
  url = "/contemplate"
  weight = 5

[[menu.main]]
  identifier = "projects"
  name = "项目"
  url = "/projects"
  weight = 6

[[menu.main]]
  identifier = "her"
  name = "Her"
  url = "/her"
  weight = 7

[[menu.main]]
  identifier = "guide"
  name = "导航"
  url = "/guide"
  weight = 8
