baseURL = "https://tarduspura.github.io/"
title = "Tardus Pura 的个人空间"
theme = "PaperMod"

# 生成设置
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  # 首页顶部显示
  homeInfoParams = { Title = "Hi，Tardus Pura here", Content = "学习 | 户外 | 创作" }
  homePostsRSS = true
  homePostsLimit = 3       # 首页显示最新 3 篇文章
  math = true              # 支持数学公式
  showMenuItems = 10

  mainSections = ["posts", "guide", "travel","her","contemplate","projects"]

[params.assets]
  customCSS = ["css/custom.css"]  

# -------------------------------
# 菜单配置（统一管理）
# -------------------------------
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "笔记"
  url = "/posts"
  weight = 3

[[menu.main]]
  identifier = "travel"
  name = "旅行&户外"
  url = "/travel"
  weight = 4

[[menu.main]]
  identifier = "contemplate"
  name = "沉思"
  url = "/contemplate"
  weight = 5

[[menu.main]]
  identifier = "projects"
  name = "项目"
  url = "/projects"
  weight = 6

[[menu.main]]
  identifier = "her"
  name = "Her"
  url = "/her"
  weight = 7

[[menu.main]]
  identifier = "guide"
  name = "导航"
  url = "/guide"
  weight = 8
